### ISSUE TITLE
Hidden desktop files do not participate in desktop ID precedence rules

### ISSUE THREAD

**Issue by Nycta-b424b3c7** [enkore/j4-dmenu-desktop#167] opened 2024-06-23 12:44 UTC
I override desktop files in `~/.local/share/applications`, to hide those that I don't want to be shown (Such as `xfce4-about.desktop` that shows "About Xfce" window, for instance).

The program seem to explicitly ignore those (I saw `Desktop file is skipped: Refusing to parse Hidden or NoDisplay desktop file.` in logs).

Can you please make this use-case viable?

**Comment by meator** [comment] 2024-06-23 13:53
Thanks for the bug report!

Sorry, I haven't considered your use case. I have even [written an unit test](https://github.com/enkore/j4-dmenu-desktop/blob/r3.0/tests/TestAppManager.cc#L798-L866) that verifies that this arguably incorrect behavior is in place. j4-dmenu-desktop r3.0 completely ignores hidden files, which is different from the behavior of r2.18.

This will be fixed in the r3.1 release.

**Comment by Nycta-b424b3c7** [comment] 2024-06-23 18:48
That's awesome, thank you very much!

**Closed as completed** 2024-06-24 09:20 UTC

**Comment by meator** [comment] 2024-06-24 09:22
Should be fixed in `develop`. Could you please verify that the issue is fixed? You can clone this repository and follow [build requirements](https://github.com/enkore/j4-dmenu-desktop?tab=readme-ov-file#build-requirements) to build the latest j4-dmenu-destkop.

**Comment by Nycta-b424b3c7** [comment] 2024-06-24 21:12
Built it from `develop` sources and it sure does work! Thank you very much!
