### ISSUE TITLE
Version r3.0: --no-exec prints to stderr instead of stdout

### ISSUE THREAD

**Issue by soulsource** [enkore/j4-dmenu-desktop#173] opened 2024-07-29 19:41 UTC
Basically what it says in the title. The behaviour of --no-exec of version 3.0 does not match the description in the man page.

I know this is no longer applicable to the current in-development state, but it might still warrant a minor release (3.0.1?) to fix it.

The problematic line is [main.cc:662](https://github.com/enkore/j4-dmenu-desktop/blob/fb52c4c3f32aaca8cd2865145aa66bfe34c83172/src/main.cc#L662).

**Comment by meator** [comment] 2024-07-29 20:05
Duplicate of #152. I'm planning to release version `r3.1` very soon which will include the fix. If you have time to spare, you can try out [the release candidate](https://github.com/enkore/j4-dmenu-desktop/releases/tag/r3.1-rc2).

**Closed as completed by meator** 2024-07-29 20:05 UTC
